# Generated by Django 4.0 on 2021-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_loc', models.CharField(max_length=100)),
                ('movie_Release', models.DateTimeField()),
                ('ticket_cost', models.IntegerField()),
                ('movie_rating', models.IntegerField()),
            ],
        ),
    ]
